/* ============================================================
   DANH SÁCH SẢN PHẨM
   ------------------------------------------------------------
   File này được xuất ra từ admin.html — mở admin.html để sửa
   bằng giao diện thay vì sửa tay ở đây. Vẫn có thể sửa tay nếu
   muốn: copy một khối {...}, dán xuống dưới, đổi chữ trong "...".
   ============================================================ */

const CATEGORIES = [
  { id: "all", label: "Tất cả" },
  { id: "table", label: "Đèn bàn" },
  { id: "ceil", label: "Đèn trần" },
  { id: "wall", label: "Đèn tường" },
  { id: "floor", label: "Đèn sàn" },
  { id: "night", label: "Đèn ngủ" },
];

const PRODUCTS = [
  {
    id: "db-02",
    name: "Đèn bàn kẹp Clip Light",
    category: "table",
    price: "280.000₫",
    desc: "Kẹp trực tiếp vào mép bàn hoặc kệ, tiết kiệm diện tích. Điều chỉnh góc chiếu 180°.",
    image: "images/placeholder-table-2.svg",
    badge: "",
  },
  {
    id: "dt-01",
    name: "Đèn trần thả Pendant tròn",
    category: "ceil",
    price: "620.000₫",
    desc: "Khung kim loại sơn tĩnh điện, dây treo chỉnh được độ cao 40–150cm.",
    image: "images/placeholder-ceil-1.svg",
    badge: "Bán chạy",
  },
  {
    id: "dt-02",
    name: "Đèn trần chùm 3 bóng",
    category: "ceil",
    price: "1.150.000₫",
    desc: "Bộ 3 chao thuỷ tinh mờ, phù hợp phòng khách trần cao từ 2m7.",
    image: "images/placeholder-ceil-2.svg",
    badge: "",
  },
  {
    id: "dtg-01",
    name: "Đèn tường hắt nến Wall Sconce",
    category: "wall",
    price: "320.000₫",
    desc: "Ánh sáng hắt lên tường tạo điểm nhấn, phù hợp hành lang và đầu giường.",
    image: "images/placeholder-wall-1.svg",
    badge: "",
  },
  {
    id: "df-01",
    name: "Đèn sàn chân gỗ Arc",
    category: "floor",
    price: "890.000₫",
    desc: "Thân cao 155cm, chân đế gỗ tần bì chắc chắn, chao vải có thể tháo giặt.",
    image: "images/placeholder-floor-1.svg",
    badge: "Bán chạy",
  },
  {
    id: "df-02",
    name: "Đèn sàn góc Tripod",
    category: "floor",
    price: "540.000₫",
    desc: "Ba chân gỗ xoè kiểu chân máy ảnh, phong cách Scandinavian.",
    image: "images/placeholder-floor-2.svg",
    badge: "",
  },
  {
    id: "table-01-en-ban-go-oc-c",
    name: "Đèn bàn gỗ óc chó Nordic",
    category: "table",
    price: "520.000₫",
    desc: "Thân gỗ óc chó nguyên khối, chao vải bố, ánh sáng vàng dịu cho góc đọc sách.",
    image: "images/placeholder-table-1.svg",
    badge: "",
  },
  {
    id: "table-02-en-ban-sac-kho",
    name: "Đèn bàn sạc không dây tích hợp",
    category: "table",
    price: "610.000₫",
    desc: "Đế đèn kiêm sạc không dây cho điện thoại, 3 mức độ sáng.",
    image: "images/placeholder-table-2.svg",
    badge: "",
  },
  {
    id: "table-03-en-ban-cam-ung",
    name: "Đèn bàn cảm ứng chạm tối giản",
    category: "table",
    price: "380.000₫",
    desc: "Chạm nhẹ để bật/tắt và chỉnh độ sáng, thân nhôm phay xước.",
    image: "images/placeholder-table-1.svg",
    badge: "",
  },
  {
    id: "table-04-en-ban-su-men-",
    name: "Đèn bàn sứ men rạn cổ điển",
    category: "table",
    price: "460.000₫",
    desc: "Chao vải lanh, đế sứ men rạn thủ công, hợp không gian tân cổ điển.",
    image: "images/placeholder-table-2.svg",
    badge: "",
  },
  {
    id: "table-05-en-ban-kep-mep",
    name: "Đèn bàn kẹp mép có cần gập",
    category: "table",
    price: "250.000₫",
    desc: "Cần gập 3 khớp linh hoạt, kẹp chắc mép bàn dày tới 5cm.",
    image: "images/placeholder-table-1.svg",
    badge: "",
  },
  {
    id: "table-06-en-ban-hinh-na",
    name: "Đèn bàn hình nấm mica",
    category: "table",
    price: "195.000₫",
    desc: "Kiểu dáng nấm nhỏ nhắn, ánh sáng ấm, hợp bàn làm việc nhỏ.",
    image: "images/placeholder-table-2.svg",
    badge: "",
  },
  {
    id: "table-07-en-ban-tre-an-",
    name: "Đèn bàn tre đan thủ công",
    category: "table",
    price: "340.000₫",
    desc: "Chao tre đan tay, ánh sáng lọc qua khe tre tạo bóng đổ đẹp mắt.",
    image: "images/placeholder-table-1.svg",
    badge: "",
  },
  {
    id: "table-08-en-ban-kim-loa",
    name: "Đèn bàn kim loại xoay 360°",
    category: "table",
    price: "295.000₫",
    desc: "Khớp xoay toàn phần, chiếu điểm rõ nét cho bàn vẽ, bàn học.",
    image: "images/placeholder-table-2.svg",
    badge: "",
  },
  {
    id: "table-09-en-ban-a-cam-t",
    name: "Đèn bàn đá cẩm thạch mini",
    category: "table",
    price: "430.000₫",
    desc: "Đế đá cẩm thạch nhân tạo, dáng tròn sang trọng cho bàn trang điểm.",
    image: "images/placeholder-table-1.svg",
    badge: "",
  },
  {
    id: "table-10-en-ban-oc-sach",
    name: "Đèn bàn đọc sách kẹp giường",
    category: "table",
    price: "210.000₫",
    desc: "Ánh sáng chiếu điểm không chói mắt, không làm phiền người bên cạnh.",
    image: "images/placeholder-table-2.svg",
    badge: "",
  },
  {
    id: "ceil-01-en-tha-tran-ma",
    name: "Đèn thả trần macramé đan tay",
    category: "ceil",
    price: "720.000₫",
    desc: "Chao đan bằng dây cotton macramé, phong cách Bohemian ấm cúng.",
    image: "images/placeholder-ceil-1.svg",
    badge: "",
  },
  {
    id: "ceil-02-en-chum-pha-le",
    name: "Đèn chùm pha lê mini phòng khách",
    category: "ceil",
    price: "2.450.000₫",
    desc: "9 tay đèn, hạt pha lê K9, tạo điểm nhấn sang trọng cho trần cao.",
    image: "images/placeholder-ceil-2.svg",
    badge: "",
  },
  {
    id: "ceil-03-en-mam-led-oi-",
    name: "Đèn mâm LED đổi 3 màu ánh sáng",
    category: "ceil",
    price: "980.000₫",
    desc: "Điều khiển từ xa, 3 chế độ màu, phù hợp phòng khách trần thấp.",
    image: "images/placeholder-ceil-1.svg",
    badge: "Mới",
  },
  {
    id: "ceil-04-en-tha-long-ma",
    name: "Đèn thả lồng mây tre đan",
    category: "ceil",
    price: "560.000₫",
    desc: "Ánh sáng ấm hắt qua lồng mây, hợp không gian mộc, nhà hàng, quán cà phê.",
    image: "images/placeholder-ceil-2.svg",
    badge: "Mới",
  },
  {
    id: "ceil-05-en-tha-cong-ng",
    name: "Đèn thả công nghiệp ống đồng",
    category: "ceil",
    price: "640.000₫",
    desc: "Phong cách industrial, thân ống đồng thau, hợp quán cà phê, bar.",
    image: "images/placeholder-ceil-1.svg",
    badge: "Mới",
  },
  {
    id: "ceil-06-en-tha-3-bong-",
    name: "Đèn thả 3 bóng so le độ cao",
    category: "ceil",
    price: "850.000₫",
    desc: "Bộ 3 bóng treo so le, dây rút chỉnh độ cao riêng từng bóng.",
    image: "images/placeholder-ceil-2.svg",
    badge: "",
  },
  {
    id: "ceil-07-en-tha-hinh-ia",
    name: "Đèn thả hình đĩa bay UFO",
    category: "ceil",
    price: "690.000₫",
    desc: "Khung nhôm mỏng, ánh sáng viền LED, kiểu dáng hiện đại.",
    image: "images/placeholder-ceil-1.svg",
    badge: "",
  },
  {
    id: "ceil-08-en-tha-chao-va",
    name: "Đèn thả chao vải hình nón úp",
    category: "ceil",
    price: "470.000₫",
    desc: "Chao vải lanh tự nhiên, ánh sáng dịu, dễ phối mọi không gian.",
    image: "images/placeholder-ceil-2.svg",
    badge: "",
  },
  {
    id: "ceil-09-en-tha-hoa-sen",
    name: "Đèn thả hoa sen gốm sứ",
    category: "ceil",
    price: "610.000₫",
    desc: "Chao gốm hình cánh sen, ánh sáng ấm toả đều, mang nét Á Đông.",
    image: "images/placeholder-ceil-1.svg",
    badge: "",
  },
  {
    id: "ceil-10-en-op-tran-tro",
    name: "Đèn ốp trần tròn viền vàng",
    category: "ceil",
    price: "730.000₫",
    desc: "Viền mạ vàng sang trọng, ánh sáng đều khắp phòng, dễ lắp đặt.",
    image: "images/placeholder-ceil-2.svg",
    badge: "",
  },
  {
    id: "wall-01-en-tuong-hinh-",
    name: "Đèn tường hình bán nguyệt",
    category: "wall",
    price: "280.000₫",
    desc: "Ánh sáng hắt tường dạng nửa vầng trăng, tối giản và tinh tế.",
    image: "images/placeholder-wall-1.svg",
    badge: "",
  },
  {
    id: "wall-02-en-tuong-au-gi",
    name: "Đèn tường đầu giường có công tắc riêng",
    category: "wall",
    price: "260.000₫",
    desc: "Lắp cạnh đầu giường, công tắc riêng không làm phiền người ngủ cùng.",
    image: "images/placeholder-wall-1.svg",
    badge: "Bán chạy",
  },
  {
    id: "wall-03-en-tuong-oi-ca",
    name: "Đèn tường đôi cánh đối xứng",
    category: "wall",
    price: "350.000₫",
    desc: "Hai cánh đèn đối xứng hai bên, hợp lắp hành lang, cầu thang.",
    image: "images/placeholder-wall-1.svg",
    badge: "Bán chạy",
  },
  {
    id: "wall-04-en-tuong-kieu-",
    name: "Đèn tường kiểu Nhật giấy dó",
    category: "wall",
    price: "310.000₫",
    desc: "Chao giấy dó truyền thống, ánh sáng mờ ảo, phong cách thiền tịnh.",
    image: "images/placeholder-wall-1.svg",
    badge: "",
  },
  {
    id: "wall-05-en-tuong-ong-t",
    name: "Đèn tường ống trúc mộc mạc",
    category: "wall",
    price: "295.000₫",
    desc: "Thân ống trúc tự nhiên, ánh sáng ấm áp cho không gian sân vườn trong nhà.",
    image: "images/placeholder-wall-1.svg",
    badge: "Bán chạy",
  },
  {
    id: "wall-06-en-tuong-chao-",
    name: "Đèn tường chao vải xếp ly",
    category: "wall",
    price: "330.000₫",
    desc: "Chao vải xếp ly tinh tế, ánh sáng dịu nhẹ cho phòng khách.",
    image: "images/placeholder-wall-1.svg",
    badge: "",
  },
  {
    id: "wall-07-en-tuong-kim-l",
    name: "Đèn tường kim loại chữ nhật",
    category: "wall",
    price: "270.000₫",
    desc: "Thiết kế vuông vức hiện đại, hắt sáng lên và xuống hai chiều.",
    image: "images/placeholder-wall-1.svg",
    badge: "",
  },
  {
    id: "wall-08-en-tuong-hinh-",
    name: "Đèn tường hình giọt nước pha lê",
    category: "wall",
    price: "420.000₫",
    desc: "Điểm nhấn pha lê nhỏ, ánh sáng lung linh cho lối vào nhà.",
    image: "images/placeholder-wall-1.svg",
    badge: "Mới",
  },
  {
    id: "floor-01-en-san-cay-ung",
    name: "Đèn sàn cây đứng 3 tầng sáng",
    category: "floor",
    price: "950.000₫",
    desc: "Ba tầng ánh sáng độc lập, phù hợp góc đọc sách nhiều lớp chiếu.",
    image: "images/placeholder-floor-1.svg",
    badge: "",
  },
  {
    id: "floor-02-en-san-bac-au-",
    name: "Đèn sàn Bắc Âu chân thép mảnh",
    category: "floor",
    price: "680.000₫",
    desc: "Chân thép sơn tĩnh điện mảnh mai, chao vải trắng tối giản.",
    image: "images/placeholder-floor-2.svg",
    badge: "",
  },
  {
    id: "floor-03-en-san-goc-pho",
    name: "Đèn sàn góc phòng khách vải lanh",
    category: "floor",
    price: "720.000₫",
    desc: "Chao vải lanh tự nhiên, ánh sáng toả rộng cho phòng khách.",
    image: "images/placeholder-floor-1.svg",
    badge: "",
  },
  {
    id: "floor-04-en-san-oc-sach",
    name: "Đèn sàn đọc sách chỉnh hướng",
    category: "floor",
    price: "590.000₫",
    desc: "Cần đèn chỉnh được góc chiếu, hợp ghế sofa, ghế bành.",
    image: "images/placeholder-floor-2.svg",
    badge: "",
  },
  {
    id: "floor-05-en-san-than-ne",
    name: "Đèn sàn thân nến gỗ cao",
    category: "floor",
    price: "780.000₫",
    desc: "Dáng thân nến thanh mảnh, chiều cao 165cm, điểm nhấn góc phòng.",
    image: "images/placeholder-floor-1.svg",
    badge: "",
  },
  {
    id: "floor-06-en-san-e-a-mar",
    name: "Đèn sàn đế đá marble giả",
    category: "floor",
    price: "890.000₫",
    desc: "Đế đá marble nhân tạo chắc chắn, thân đồng thau sang trọng.",
    image: "images/placeholder-floor-2.svg",
    badge: "",
  },
  {
    id: "floor-07-en-san-cong-ch",
    name: "Đèn sàn cong chiếu bàn ăn",
    category: "floor",
    price: "1.050.000₫",
    desc: "Thân cong vươn xa 90cm, chiếu sáng trực tiếp bàn ăn, bàn trà.",
    image: "images/placeholder-floor-1.svg",
    badge: "",
  },
  {
    id: "floor-08-en-san-long-ma",
    name: "Đèn sàn lồng mây đan thủ công",
    category: "floor",
    price: "640.000₫",
    desc: "Chao mây đan tay, ánh sáng ấm mộc mạc cho không gian sân vườn.",
    image: "images/placeholder-floor-2.svg",
    badge: "",
  },
  {
    id: "night-01-en-ngu-cam-ung",
    name: "Đèn ngủ cảm ứng hình trăng khuyết",
    category: "night",
    price: "220.000₫",
    desc: "Chạm nhẹ đổi 3 mức sáng, sạc USB tiện lợi, quà tặng ý nghĩa.",
    image: "images/placeholder-table-1.svg",
    badge: "",
  },
  {
    id: "night-02-en-ngu-hinh-na",
    name: "Đèn ngủ hình nấm silicon mềm",
    category: "night",
    price: "180.000₫",
    desc: "Chất liệu silicon an toàn cho bé, ánh sáng dịu không chói mắt.",
    image: "images/placeholder-table-2.svg",
    badge: "",
  },
  {
    id: "night-03-en-ngu-khoi-ph",
    name: "Đèn ngủ khối pha lê khắc 3D",
    category: "night",
    price: "350.000₫",
    desc: "Khắc hình 3D bên trong khối pha lê, đổi màu qua remote.",
    image: "images/placeholder-table-1.svg",
    badge: "",
  },
  {
    id: "night-04-en-ngu-hen-gio",
    name: "Đèn ngủ hẹn giờ tắt tự động",
    category: "night",
    price: "240.000₫",
    desc: "Hẹn giờ tắt 15-60 phút, ánh sáng vàng ấm giúp dễ ngủ hơn.",
    image: "images/placeholder-table-2.svg",
    badge: "",
  },
  {
    id: "night-05-en-ngu-hinh-ma",
    name: "Đèn ngủ hình mây bồng bềnh",
    category: "night",
    price: "260.000₫",
    desc: "Thiết kế đám mây dễ thương, hợp phòng trẻ em, ánh sáng an toàn.",
    image: "images/placeholder-table-1.svg",
    badge: "",
  },
  {
    id: "night-06-en-ngu-a-muoi-",
    name: "Đèn ngủ đá muối Himalaya",
    category: "night",
    price: "310.000₫",
    desc: "Đá muối tự nhiên, ánh sáng hồng ấm, được cho là giúp thư giãn.",
    image: "images/placeholder-table-2.svg",
    badge: "",
  },
  {
    id: "night-07-en-ngu-mini-ke",
    name: "Đèn ngủ mini kẹp đầu giường",
    category: "night",
    price: "165.000₫",
    desc: "Kẹp gọn gàng vào thành giường, tiết kiệm diện tích tủ đầu giường.",
    image: "images/placeholder-table-1.svg",
    badge: "",
  },
  {
    id: "night-08-en-ngu-hinh-ch",
    name: "Đèn ngủ hình chú thỏ gốm sứ",
    category: "night",
    price: "285.000₫",
    desc: "Gốm sứ tráng men an toàn, ánh sáng ấm dịu cho phòng bé.",
    image: "images/placeholder-table-2.svg",
    badge: "",
  },
];
